blockchain_settings:
  block_size: 2
  target_hash: 0fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
  block_confirmation_depth: 2
  mining_reward: 50
  review_reward: 10
  reward_half_time: 100
  mining_timeout: 25
  protocols:
    get_blocks:
      timeout: 5
genesis_block:
  block_hash: 00000000b4d5c50efadb20ff99f46578b59ce279
  previous_hash: 0000abcd
  nonce: 0
  target_hash: 000000ffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
  timestamp: 1733339909
  merkle_root: 00000000b4d5c50efadb20ff99f46578b59ce2365
  transaction_count: 10
  transactions:
    id: 8b728e373bdc6a3c9e4bfbfe5c52c2df3a24b1c2167c7e30de82a4c0e8699e8b
    data: "Geneis Data"
    outputs:
      - id: genesis_tx_0:0
        address: 00288852597a4a915452b9ecca456eab3dcf47e151d97b5c65 #1
        amount: 50
      - id: genesis_tx_0:1
        address: 0030456b55986f5eddb0fcffd7bf3968e9ad20a335d30a24f9 #2
        amount: 50
      - id: genesis_tx_0:2
        address: 00cc1f12d32fce22ad0a15fc7ffe67eb9f4003f081ee297450 #3
        amount: 50
      - id: genesis_tx_0:3
        address: 00ef349ef7ffba69d3ad1bd52723318138a5131b0dadf1f908 #4
        amount: 50
      - id: genesis_tx_0:4
        address: 00508b6411f3fea956d121d79a27bb5316d779e98d6341719b #5
        amount: 50
      - id: genesis_tx_0:5
        address: 0052bfe71e6ca6e9ba167a45b54536a6e4b07f2c0acd5a80fa #6
        amount: 50
      - id: genesis_tx_0:6
        address: 00ec4c4d051ce49faf012ddb9e50c73d6451990099b0a002cd #7
        amount: 50
      - id: genesis_tx_0:7
        address: 00200f06071db8ad5439bf9383b3956d0fe88cd1e651889c8e #8
        amount: 50
      - id: genesis_tx_0:8
        address: 009efa5cfc420b047d49309a5523d424ef36e8828dc753225b #9
        amount: 50
      - id: genesis_tx_0:9
        address: 006c645c36a4184b4367fb28b9077664c48fb0e67296ee4fb2 #10
        amount: 50
nodes:
  node1:
    wallet:
      private_key: |
        -----BEGIN EC PRIVATE KEY-----
        MHcCAQEEIMnr3kKzH/bk0aOcKompiuNJbYUP8xRIfFpwrP2ZbMUIoAoGCCqGSM49
        AwEHoUQDQgAEe74UOfAykGY01Zt53w4Cjw0FDrSRvHyDpo3+4BqCPAHkFJmLTijS
        6cE5CbOkOmfmiexYMHnHFlQXxsFXTJmbTA==
        -----END EC PRIVATE KEY-----
    transactions:
      - type: purchase
        amount: 5
        delay: 1
        buyer_address: 00288852597a4a915452b9ecca456eab3dcf47e151d97b5c65 #1
        seller_address: 0030456b55986f5eddb0fcffd7bf3968e9ad20a335d30a24f9 #2
        product_id: product1
        fee: 10
      - type: purchase
        amount: 5
        delay: 30
        buyer_address: 00288852597a4a915452b9ecca456eab3dcf47e151d97b5c65 #1
        seller_address: 0030456b55986f5eddb0fcffd7bf3968e9ad20a335d30a24f9 #2
        product_id: product2
        fee: 10
      - type: review
        delay: 80
        reviewer_address: 00288852597a4a915452b9ecca456eab3dcf47e151d97b5c65 #1
        product_id: product1
        rating: 4
  node2:
    wallet:
      private_key: |
        -----BEGIN EC PRIVATE KEY-----
        MHcCAQEEIAhJyAnOwAnlplwa0TIgtnHFCr0Bt0+bLiDTWQX4t51goAoGCCqGSM49
        AwEHoUQDQgAEcZBpfwItB268s2NsVxsuj1dC2YTXZVGgWtvzQlMmyf6izKCzQMYT
        rFo7ve7DJgw0Kdcjy9k1rfcTNlELxi5k1w==
        -----END EC PRIVATE KEY-----
    transactions:
      - type: purchase
        amount: 5
        delay: 5
        buyer_address: 0030456b55986f5eddb0fcffd7bf3968e9ad20a335d30a24f9 #2
        seller_address: 00288852597a4a915452b9ecca456eab3dcf47e151d97b5c65 #1
        product_id: product3
        fee: 2
      - type: purchase
        amount: 5
        delay: 88
        buyer_address: 0030456b55986f5eddb0fcffd7bf3968e9ad20a335d30a24f9 #2
        seller_address: 00288852597a4a915452b9ecca456eab3dcf47e151d97b5c65 #1
        product_id: product4
        fee: 2
  node3:
    wallet:
      private_key: |
        -----BEGIN EC PRIVATE KEY-----
        MHcCAQEEIJKPhXOk+ZDF9vikO/rDJlPTz6KDFpKS+2ahGa/rVSqFoAoGCCqGSM49
        AwEHoUQDQgAE0gUmmKWZXCQZhHcR5hB1MAXdN1RKGXTOUoynb64CiBzF42aC/mYS
        61U6DNzhYFPb/CQY9EpkPYeXARr5Vi+KiA==
        -----END EC PRIVATE KEY-----
    transactions:
      - type: purchase
        amount: 5
        delay: 45
        buyer_address: 00cc1f12d32fce22ad0a15fc7ffe67eb9f4003f081ee297450 #3
        seller_address: 00288852597a4a915452b9ecca456eab3dcf47e151d97b5c65 #1
        product_id: product5
        fee: 2
  node4:
    wallet:
      private_key: |
        -----BEGIN EC PRIVATE KEY-----
        MHcCAQEEIKCJhr6/3BrRVvKqt2xnc6M24HkqplS2LKzy1bNtn4CvoAoGCCqGSM49
        AwEHoUQDQgAEvNFwZvV/xhkNCb1a8LhZP75yBsU4X1RUM7QQc2yhm6ckgyjDijw9
        6DPmnXTBL/s9mHcYanKec3OMZ1hs3fVOfw==
        -----END EC PRIVATE KEY-----
    transactions:
      - type: purchase
        amount: 55
        delay: 10
        buyer_address: 00ef349ef7ffba69d3ad1bd52723318138a5131b0dadf1f908 #4
        seller_address: 00508b6411f3fea956d121d79a27bb5316d779e98d6341719b #5
        product_id: product5
        fee: 5
      - type: review
        delay: 90
        reviewer_address: 00ef349ef7ffba69d3ad1bd52723318138a5131b0dadf1f908 #4
        product_id: product5
        rating: 5
  node5:
    wallet:
      private_key: |
        -----BEGIN EC PRIVATE KEY-----
        MHcCAQEEIArWP8mrzGNUpkNbzWijCQsHMVx7+wv+dJ0mMPZDHe6AoAoGCCqGSM49
        AwEHoUQDQgAEqYTZyzdpZBjMFb48RXvpjtFBD+MZbfIzO6U+P2cE4ClrsIDI7yft
        N/XpQfhEfFnoMA9WD+Xw5egwGikpnGTeXQ==
        -----END EC PRIVATE KEY-----
    transactions:
      - type: purchase
        amount: 5
        delay: 45
        buyer_address: 00508b6411f3fea956d121d79a27bb5316d779e98d6341719b #5
        seller_address: 0030456b55986f5eddb0fcffd7bf3968e9ad20a335d30a24f9 #2
        product_id: product6
        fee: 2
