services:
  # Nodes in Network 1
  node1:
    image: trustify
    hostname: "node1"
    container_name: "node1"
    networks:
      - network1

  node2:
    image: trustify
    hostname: "node2"
    container_name: "node2"
    networks:
      - network1

  node3:
    image: trustify
    hostname: "node3"
    container_name: "node3"
    networks:
      - network1
  
  node4:
    image: trustify
    hostname: "node4"
    container_name: "node4"
    networks:
      - network1

  # Bridge Nodes
  node5:
    image: trustify
    hostname: "node5"
    container_name: "node5"
    privileged: true
    networks:
      - network1
      - network2


networks:
  network1:
    driver: bridge